In [24]:
import numpy as nump

# Define two example matrices
A = nump.array([[6, 4, 0], [3, 1, 3], [2, 5, 5]])
B = nump.array([[4, 2, 3], [5, 7, 1], [1, 2, 2]])

print("A = [[6, 4, 0], [3, 1, 3], [2, 5, 5]]")
print("B = [[4, 2, 3], [5, 7, 1], [1, 2, 2]]")
print("A + B")

# Matrix addition
result_Matrix_addition = A + B
print("result Matrix addition=")
print(result_Matrix_addition)

print("")
print("..........................")
print("")

# Define two example matrices
A = nump.array([[6, 4], [3, 1], [2, 5]])
B = nump.array([[4, 3], [5, 7], [1, 2]])

print("A = [[6, 4], [3, 1], [2, 5]]")
print("B = [[4, 3], [5, 7], [1, 2]]")
print("A - B")

# Matrix subtraction
result_Matrix_subtraction = A - B
print("result Matrix subtraction=")
print(result_Matrix_subtraction)

print("")
print("..........................")
print("")

# Define an example matrix
A = nump.array([[6, 4, 0], [3, 1, 3], [2, 5, 5]])

print("A = [[6, 4, 0], [3, 1, 3], [2, 5, 5]]")
print("3* A")

# Scalar multiplication
result_Scalar_multiplication = 3 * A
print("result Scalar multiplication=")
print(result_Scalar_multiplication)

print("")
print("..........................")
print("")

# Define two example matrices
A = nump.array([[6, 4], [3, 1], [2, 5]])
B = nump.array([[4, 2, 3], [5, 7, 1]])

print("A = [[6, 4], [3, 1], [2, 5]]")
print("B = [[4, 2, 3], [5, 7, 1]]")
print("A * B")

# Matrix multiplication
result_Matrix_multiplication = nump.dot(A, B)
print("result Matrix multiplication=")
print(result_Matrix_multiplication)

A = [[6, 4, 0], [3, 1, 3], [2, 5, 5]]
B = [[4, 2, 3], [5, 7, 1], [1, 2, 2]]
A + B
result Matrix addition=
[[10  6  3]
 [ 8  8  4]
 [ 3  7  7]]

..........................

A = [[6, 4], [3, 1], [2, 5]]
B = [[4, 3], [5, 7], [1, 2]]
A - B
result Matrix subtraction=
[[ 2  1]
 [-2 -6]
 [ 1  3]]

..........................

A = [[6, 4, 0], [3, 1, 3], [2, 5, 5]]
scalar = 3
scalar * A
result Scalar multiplication=
[[18 12  0]
 [ 9  3  9]
 [ 6 15 15]]

..........................

A = [[6, 4], [3, 1], [2, 5]]
B = [[4, 2, 3], [5, 7, 1]]
A * B
result Matrix multiplication=
[[44 40 22]
 [17 13 10]
 [33 39 11]]
