In [7]:
import numpy as nump

# Define two example matrices
A = nump.array([[3, 4], [2, 7]])
B = nump.array([[5, 6], [2, 8]])

print("A = [[3, 4], [2, 7]]")
print("B = [[5, 6], [2, 8]]")
print("A + B")

# Matrix addition
result_Matrix_addition = A + B
print("Matrix addition=") 
print(result_Matrix_addition)

print("")
print("---------------------------")
print("")

# Define two example matrices
A = nump.array([[3, 4], [2, 7]])
B = nump.array([[5, 6], [2, 8]])

print("A = [[3, 4], [2, 7]]")
print("B = [[5, 6], [2, 8]]")
print("A - B")

# Matrix subtraction
result_Matrix_subtraction = A - B
print("Matrix subtraction=")
print(result_Matrix_subtraction)

print("")
print("---------------------------")
print("")

# Define an example matrix
A = nump.array([[7, 8], [4, 9], [5, 5]])

print("A = [[7, 8], [4, 9], [5, 5]]")
print("5* A")

# Scalar multiplication
result_Scalar_multiplication = 5 * A
print("Scalar multiplication=")
print(result_Scalar_multiplication)

print("")
print("---------------------------")
print("")

# Define two example matrices
A = nump.array([[7, 8], [4, 9], [5, 5]])
B = nump.array([[4, 2, 2], [5, 7, 9]])

print("A = [[7, 8], [4, 9], [5, 5]]")
print("B = [[4, 2, 2], [5, 7, 9]]")
print("A * B")

# Matrix multiplication
result_Matrix_multiplication = nump.dot(A, B)
print("Matrix multiplication=")
print(result_Matrix_multiplication)


A = [[3, 4], [2, 7]]
B = [[5, 6], [2, 8]]
A + B
Matrix addition=
[[ 8 10]
 [ 4 15]]

---------------------------

A = [[3, 4], [2, 7]]
B = [[5, 6], [2, 8]]
A - B
Matrix subtraction=
[[-2 -2]
 [ 0 -1]]

---------------------------

A = [[7, 8], [4, 9], [5, 5]]
5* A
Scalar multiplication=
[[35 40]
 [20 45]
 [25 25]]

---------------------------

A = [[7, 8], [4, 9], [5, 5]]
B = [[4, 2, 2], [5, 7, 9]]
A * B
Matrix multiplication=
[[68 70 86]
 [61 71 89]
 [45 45 55]]
